----------------------------------------------
-- DROP.SQL
----------------------------------------------

DROP TABLE Resultat
/
DROP TABLE Evaluation
/
DROP TABLE NoteLettree
/
DROP TABLE InscriptionGroupeCours
/
DROP TABLE StatutInscription
/
DROP TABLE InscriptionProgramme
/
DROP TABLE Etudiant
/
DROP TABLE ProgrammeEtudes
/
DROP TABLE IntervalleNote
/
DROP TABLE StatutTransferBordereau
/
DROP TABLE GroupeCours
/
DROP TABLE SessionGC
/
DROP TABLE Cours
/
DROP TABLE Employe
/
DROP TABLE Departement
/